In [1]:
# Cell 1: Import necessary libraries
import pandas as pd

# Cell 2: Load the CSV file
file_path = '../masterworks_administrative_services,_llc_raw_bills_data_as_of_31-08-2024.csv'

# Load the raw data from the CSV file
raw_data = pd.read_csv(file_path)

# Display the first few rows to understand the structure
print("First few rows of the dataset:")
raw_data.head()

# Cell 3: Filter the data by vendor name
# Ask for vendor name input (in a Jupyter Notebook, you'll input this manually)
vendor_name_input = input("Enter vendor name to filter by (case-insensitive): ")

# Filter the DataFrame by the given vendor name (case-insensitive)
filtered_data = raw_data[raw_data['vendor'].str.contains(vendor_name_input, case=False, na=False)]

# Check if the filter returned any data
if not filtered_data.empty:
    # Display the filtered data
    print(f"\nFiltered Data for Vendor '{vendor_name_input}':")
    display(filtered_data)
else:
    print(f"No data found for vendor '{vendor_name_input}'.")

# Cell 4: Basic EDA on the filtered data
if not filtered_data.empty:
    # Display some summary statistics
    print("\nSummary Statistics for the filtered data:")
    display(filtered_data.describe())

    # Group by vendor and sum amounts (if 'amount' column exists)
    if 'amount' in filtered_data.columns:
        vendor_totals = filtered_data.groupby('vendor')['amount'].sum()
        print("\nTotal outstanding amount per vendor:")
        display(vendor_totals)
else:
    print("No filtered data to analyze.")

# Cell 5: Save the filtered data to a new CSV file (optional)
if not filtered_data.empty:
    output_filename = f"{vendor_name_input.replace(' ', '_').lower()}_filtered_bills.csv"
    filtered_data.to_csv(output_filename, index=False)
    print(f"\nFiltered data saved to '{output_filename}'.")

First few rows of the dataset:

Filtered Data for Vendor 'Wise Publishing Inc':

,inventory_line_items,paid_at,invoice_number,line_items,created_at,deep_link_url,entity_id,remote_id,due_at,invoice_urls,memo,status,issued_at,accounting_field_selections,amount,id,vendor,payment,bill_owner
172,[],2024-08-13T00:00:00+00:00,3998,"[{'amount': {'currency_code': 'USD', 'amount':...",2024-07-16T13:13:22+00:00,https://8348504.app.netsuite.com/app/accountin...,b9b3b267-c0cf-48ff-bdcc-615c73edabc3,643014,2024-07-30T00:00:00+00:00,['https://receipts.ramp.com/invoices/masterwor...,10905 - Wise Publishing Email & Push Campaigns...,PAID,2024-07-01T00:00:00+00:00,[],"{'currency_code': 'USD', 'amount': 375000}",c64e657d-940f-471e-b361-b9d8b7017242,"{'type': 'BUSINESS', 'remote_code': None, 'rem...",NaN,"{'last_name': 'Luna', 'id': '0bb9a254-cc23-468..."

Summary Statistics for the filtered data:

       remote_id
count        1.0
mean    643014.0
std          NaN
min     643014.0
25%     643014.0
50%     643014.0
75%     643014.0
max     643014.0

Total outstanding amount per vendor:

vendor
{'type': 'BUSINESS', 'remote_code': None, 'remote_id': '19837', 'remote_name': 'Wise Publishing Inc'}    {'currency_code': 'USD', 'amount': 375000}
Name: amount, dtype: object

Filtered data saved to 'wise_publishing_inc_filtered_bills.csv'.